project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: about

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



